package order

import "github.com/go-turk/afyon/internal/order/domain"

type OrderRepository interface {
	CreateTable() error
	// Save ...
	Save(order *domain.Order) error
	// FindAll ...
	FindAll(ID ...int) ([]domain.Order, error)
	// FindByID ...
	FindByID(id int) (domain.Order, error)
	// AppendItem ...
	AppendItem(orderID int, itemID int) error
	// DecreaseItem ...
	DecreaseItem(orderID int, itemID int) error
	// Delete ...
	Delete(id int) error
	// Update ...
	Update(order domain.Order) error
}

type ItemRepository interface {
	CreateTable() error
	// Save ...
	Save(item *domain.Item) error
	// FindAll ...
	FindAll(ID ...int) ([]domain.Item, error)
	// FindByID ...
	FindByID(id int) (*domain.Item, error)
	// Delete ...
	Delete(id int) error
}
